# Generated by Django 3.1.3 on 2020-12-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='書籍名')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='著者')),
                ('issue_date', models.DateField(verbose_name='発行日')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='最終購入日')),
                ('all_stock', models.IntegerField(default='1', verbose_name='在庫')),
                ('last_stock', models.IntegerField(default='1', verbose_name='レンタル可能数')),
                ('disposal_status', models.CharField(blank=True, max_length=10, null=True, verbose_name='廃棄')),
            ],
            options={
                'verbose_name_plural': '書籍',
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='書籍名')),
                ('author', models.CharField(max_length=100, verbose_name='著者')),
                ('order_date', models.DateField(verbose_name='注文日')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='発行日')),
                ('order_quantity', models.IntegerField(default='1', verbose_name='注文数')),
                ('book_url', models.TextField(verbose_name='URL')),
            ],
            options={
                'verbose_name_plural': '注文',
                'db_table': 'bookOrder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='社員ID')),
                ('crew_num', models.CharField(max_length=6, verbose_name='社員番号')),
                ('name', models.CharField(max_length=15, verbose_name='氏名')),
                ('kana', models.CharField(max_length=30, verbose_name='しめい')),
                ('enter_date', models.DateField(verbose_name='入社日')),
                ('position', models.CharField(max_length=10, verbose_name='役職')),
                ('mail', models.EmailField(blank=True, max_length=50, null=True, verbose_name='メールアドレス')),
            ],
            options={
                'verbose_name_plural': '社員',
                'db_table': 'crew',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disposal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_date', models.DateField(blank=True, null=True, verbose_name='廃棄日')),
            ],
            options={
                'verbose_name_plural': '廃棄',
                'db_table': 'disposal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LargeCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, verbose_name='大カテゴリ')),
            ],
            options={
                'verbose_name_plural': '大カテゴリ',
                'db_table': 'largeCategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(verbose_name='レンタル申請日')),
                ('rental_date', models.DateField(verbose_name='レンタル日')),
                ('return_date', models.DateField(verbose_name='返却日')),
            ],
            options={
                'verbose_name_plural': 'レンタル',
                'db_table': 'rental',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.IntegerField(verbose_name='10段階評価')),
                ('review', models.TextField(max_length=255, verbose_name='レビュー')),
            ],
            options={
                'verbose_name_plural': 'レビュー',
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SmallCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40, verbose_name='小カテゴリ')),
            ],
            options={
                'verbose_name_plural': '小カテゴリ',
                'db_table': 'smallCategory',
                'managed': False,
            },
        ),
    ]
